import * as React from "react";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js'
// }
import { Inter } from "next/font/google";
import Metadata from "../Metadata";
import { Footer, Header } from "~/components/organisms";
const poppins = Inter({
	subsets: ["latin"],
	preload: true,
	weight: ["400", "100", "200", "300", "500", "600", "700", "800", "900"],
});

interface MainLayoutProps {
	children: React.ReactNode;
}

function MainLayout({ children }: MainLayoutProps) {
	return (
		<div className={poppins.className}>
			<Metadata title="E-Learning" description="Khám phá E-Learning" />
			{children}
		</div>
	);
}

const HFLayout = ({ children }: MainLayoutProps) => (
	<MainLayout>
		<Header />
		{children}
		<Footer />
	</MainLayout>
);

const DefaultLayout = ({ children }: MainLayoutProps) => (
	<MainLayout>{children}</MainLayout>
);
const FooterLayout = ({ children }: MainLayoutProps) => (
	<MainLayout>{children}</MainLayout>
);
export default MainLayout;
export { HFLayout, DefaultLayout, FooterLayout };
